import { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";

export const metadata: Metadata = {
  title: {
    default: "Next.js default Title",
    template: "%s | Template",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body>
          <header>
            <p style={{ backgroundColor: "lightblue", padding: "1rem" }}>
              Header
            </p>
          </header>
          {children}
          <footer>
            <p style={{ backgroundColor: "ghostwhite", padding: "1rem" }}>
              Footer
            </p>
          </footer>
        </body>
      </ThemeProvider>
    </html>
  );
}
