export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <p style={{ backgroundColor: "lightblue", padding: "1rem" }}>
            Header
          </p>
        </header>
        {children}
        <footer>
          <p style={{ backgroundColor: "ghostwhite", padding: "1rem" }}>
            Footer
          </p>
        </footer>
      </body>
    </html>
  );
}
